apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default

spec:
  replicas: 3

  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp

    spec:
      containers:
      - name: myapp
        image: vadivelu123/parking_app:f7c9faab7598c51c6c012b20f63437e0a084a984

        ports:
        - containerPort: 8080
